extends SceneTree
var failures = 0
var checks = 0
var sim: Simulation

func _initialize() -> void: call_deferred("run")
func check(value: bool, label: String) -> void:
 checks += 1
 if not value: failures += 1; push_error("OPERATIONS_FAIL " + label)
func order(role: String, action: String, args: Dictionary = {}, principal: String = "local") -> bool:
 var result = sim.command(role, action, args, principal)
 check(result.ok, action + ": " + result.message)
 return result.ok
func ticks(seconds: float) -> void:
 for i in ceili(seconds * 30): sim.tick(1.0 / 30)
func fresh() -> void:
 sim = Simulation.new()
 sim.start(Catalog.missions()[0])
func run() -> void:
 fresh()
 var before = sim.state.duplicate(true)
 check(not sim.command("mando", "warp", {"level": 1}).ok, "station permission enforced")
 check(before == sim.state, "rejected order atomic")
 check(not sim.command("navegacion", "warp", {"level": NAN}).ok, "NaN not accepted")
 check(not sim.command("navegacion", "warp", {"level": 1.5}).ok, "warp discrete levels")
 order("navegacion", "helm", {"heading": 0.0, "throttle": 1.0})
 order("navegacion", "warp", {"level": 2})
 ticks(7)
 check(sim.state.ship.speed > 400 and sim.state.ship.energy < 100, "warp accelerates and consumes reactor power")
 fresh()
 order("navegacion", "jump", {"distance": 1200})
 check(sim.state.ship.position[0] == 0, "jump is delayed")
 ticks(5.2)
 check(sim.state.ship.position[0] >= 1200 and sim.state.operations.maneuver < 25, "jump completes after charging and consumes charge")
 check(not sim.command("navegacion", "jump", {"distance": 100}).ok, "jump cannot be spammed")
 fresh()
 order("navegacion", "strafe", {"amount": -1.0})
 check(sim.state.ship.position[1] < -80 and sim.state.operations.maneuver == 70, "port strafe consumes maneuver charge")
 order("navegacion", "request_dock", {"target": "kaia"})
 order("navegacion", "abort_dock")
 ticks(1)
 check(sim.state.ship.docked.is_empty() and sim.state.ship.throttle == 0, "abort approach leaves ship free")
 order("navegacion", "request_dock", {"target": "kaia"})
 ticks(25)
 check(sim.state.ship.docked == "kaia", "approach reaches actual docking by simulation")
 fresh()
 order("ingenieria", "coolant_level", {"system": "armas", "value": 5.0})
 check(not sim.command("ingenieria", "coolant_level", {"system": "motores", "value": 4.0}).ok, "coolant total bounded")
 sim.state.ship.systems.armas.heat = 80
 ticks(2)
 check(sim.state.ship.systems.armas.heat < 61, "distributed coolant cools the selected system")
 order("ingenieria", "shield_frequency", {"frequency": 12})
 check(not sim.state.ship.shields_enabled, "frequency adjustment disables shields")
 check(not sim.command("armas", "shields", {"enabled": true}).ok, "calibrating shields cannot be enabled")
 ticks(5.1)
 order("armas", "shields", {"enabled": true})
 fresh()
 var enemy = sim.contact("zaindari")
 if enemy.is_empty():
  enemy = sim.state.contacts.back()
 enemy.kind = "hostile"
 enemy.identified = true
 enemy.position = [400.0, 0.0]
 order("armas", "tube_load", {"tube": 0, "ammo": "emp"})
 check(not sim.command("armas", "tube_fire", {"tube": 0, "target": enemy.id}).ok, "tube cannot fire before loading")
 ticks(4.1)
 order("armas", "tube_fire", {"tube": 0, "target": enemy.id})
 check(enemy.attack_at > sim.state.time + 17, "EMP inhibits enemy attacks")
 order("armas", "tube_load", {"tube": 0, "ammo": "nuke"})
 order("armas", "tube_unload", {"tube": 0})
 check(sim.state.operations.ammo.nuke == 2, "unload returns scarce ammunition")
 order("armas", "weapon_target", {"target": enemy.id})
 ticks(2)
 check(enemy.hull < 100, "target lock fires actual beams")
 order("armas", "weapon_target", {"target": ""})
 fresh()
 order("comunicaciones", "comm_open", {"target": "argi"})
 order("comunicaciones", "comm_message", {"text": "Informe de situación"})
 check(sim.state.operations.comms.messages.size() >= 3, "message and reply retained")
 order("comunicaciones", "comm_reply", {"reply": "estado"})
 order("comunicaciones", "comm_close")
 check(not sim.command("comunicaciones", "comm_reply", {"reply": "estado"}).ok, "no reply without a channel")
 fresh()
 order("enlace", "waypoint_add", {"name": "Norte", "bearing": 0.0, "distance": 500.0})
 var id = sim.state.operations.waypoints[0].id
 order("navegacion", "route_follow", {"id": id})
 ticks(15)
 check(sim.state.operations.route.is_empty() and absf(sim.state.ship.position[0] - 500) < 50, "waypoint navigation arrives and brakes")
 order("enlace", "waypoint_move", {"id": id, "bearing": 90.0, "distance": 600.0})
 order("enlace", "waypoint_remove", {"id": id})
 check(sim.state.operations.waypoints.is_empty(), "waypoint lifecycle")
 fresh()
 sim.state.ship.systems.motores.health = 20
 order("reparaciones", "crew_move", {"crew": "equipo-1", "system": "motores"})
 ticks(2)
 check(sim.state.ship.systems.motores.health == 20, "crew cannot repair before reaching the room")
 ticks(10)
 check(sim.state.ship.systems.motores.health >= 45 and sim.state.ship.parts == 22, "moving crew repairs with actual supplies")
 order("ingenieria", "auto_repair", {"enabled": true})
 ticks(12)
 check(sim.state.ship.systems.motores.health > 45, "automatic crew dispatch works")
 fresh()
 var far = sim.state.contacts.back()
 far.position = [2000.0, 0.0]
 far.jammed = false
 check(not sim.command("sensores", "scan", {"target": far.id}).ok, "remote contact outside ship scanner")
 order("enlace", "probe", {"target": far.id})
 order("enlace", "science_link", {"target": far.id})
 order("sensores", "scan", {"target": far.id})
 ticks(3)
 check(far.identified, "science probe extends scan origin")
 order("sensores", "database_record", {"target": far.id})
 check(sim.state.campaign.discoveries.size() == 1, "discoveries persist with campaign")
 check(LocalStorage.validate_state(sim.state).is_empty(), "extended state validates")
 var saved = JSON.parse_string(JSON.stringify(sim.state))
 check(LocalStorage.validate_state(saved).is_empty(), "JSON round trip preserves operations")
 saved.operations.tubes[0].remaining = -1
 check(not LocalStorage.validate_state(saved).is_empty(), "corrupt operation rejected before restore")
 fresh()
 check(not sim.command("ingenieria", "destruct_arm", {}).ok, "arming requires deliberate confirmation")
 order("ingenieria", "destruct_arm", {"confirmation": "ITSASO"}, "engineering-peer")
 check(sim.snapshot().operations.destruct.codes.is_empty(), "telemetry never receives codes")
 check(sim.snapshot("ingenieria").operations.destruct.codes.keys() == ["ingenieria"], "recipient sees only own code")
 check(sim.snapshot("navegacion").operations.destruct.codes.is_empty(), "other station cannot see codes")
 var codes = sim.state.operations.destruct.codes.duplicate()
 order("ingenieria", "destruct_confirm", {"code": codes.ingenieria}, "engineering-peer")
 check(not sim.command("mando", "destruct_confirm", {"code": codes.mando}, "engineering-peer").ok, "same peer cannot confirm by switching roles")
 order("mando", "destruct_confirm", {"code": codes.mando}, "captain-peer")
 order("armas", "destruct_confirm", {"code": codes.armas}, "weapons-peer")
 ticks(2)
 check(sim.state.operations.destruct.remaining < 14 and sim.state.ship.hull > 0, "countdown starts only after all confirmations")
 order("ingenieria", "destruct_cancel")
 ticks(16)
 check(sim.state.ship.hull > 0, "cancel stops detonation")
 order("ingenieria", "destruct_arm", {"confirmation": "ITSASO"})
 for role in ShipOperations.CONFIRMERS: order(role, "destruct_confirm", {"code": sim.state.operations.destruct.codes[role]})
 ticks(16)
 check(sim.state.status == "lost", "confirmed sequence eventually destroys the ship")
 print("OPERATIONS_TESTS ", checks, " checks; ", failures, " failures")
 quit(1 if failures else 0)
